# Capstone Project
# File: benchDB.R
#   builds the benchmark database
#   Loads Corpus, cleans it, generates DTM, DFM (frequency), DSM (score)
#   Loads Corpus (files created by fixRawBench.R)
#     bench/unix.xx.txt

print("Started script: benchDB.R")
# Got to project directory and load tools
prj.dir <- file.path(Sys.getenv("HOME"),"git","NLPCapstone")
setwd(prj.dir)
print(paste("Current directory: ",getwd()))

# load resources
source("nlpTools.R")

#Switch to process corpus directory
source("toBenchDir.R")

# bench.dir set in toBenchDir.R
text.files <- dir(".",pattern="unix.*")
print(paste("Directory: ",getwd()))
print(paste("Directory Files: ",paste0(text.files,collapse=", ")))

# select only a fraction of the processed corpus
# In this case 10% of the original data for each file.
# s.text is a list with each element one sample of the corpus
# the corpus consists of 3 files of text.
s.text <- lapply(c(0.20),sampleText,text.files)

# Building corpus from sample files generated by sampleText function.
corpus <- lapply(s.text,buildCorpus)

# Structure of corpus:
# This is a list. Each element corresponds to a sample.
# Each sample is an list containing an object, one for each text file (a document)
# The object contains two data members, content and meta, for the text file.
#
# For example, to access the text of text file 2 in sample 1:
#   corpus[[1]][2]$content
#
# The content is a character vector with multiple entries with multiple
# lines of text per entry in the vector.

# Perform operations on the corpus
# First clean it.
clean.corpus <- lapply(corpus,purify.corpus)

#  put in file names
# doing for loop because due to scoping rules it does not stick otherwise
for(j in seq(clean.corpus)){
  for(k in seq(clean.corpus[[j]])){ 
    meta(clean.corpus[[j]][[k]],"id") <- text.files[k]
  }
}

print("Saving raw corpus and clean corpus.")
if(file.exists("corpus.r")){
  file.remove("corpus.r")
}
save(corpus,clean.corpus,file="corpus.r")
print("Finished saving corpus stuff.")

# load corpus
print("Loading corpus.")
load("corpus.r")

# Second, Generate DTMS for clean corpus
print("Generating DTMS for clean corpus.")
dtms <- lapply(clean.corpus,buildDTM) # using default 4-gram as maximum
for(k in seq_along(clean.corpus)){
  names(dtms[[k]])<- c("unigram","bigram","trigram","quadgram")
}

print("Saving DTMS.")
if(file.exists("dbdtms.r")){
  file.remove("dbdtms.r")
}
save(dtms,file="dbdtms.r")
print("Finished saving DTMS.")

# Create list of quadgrams
quads <- dtms[[1]]$quadgram$dimnames$Terms
if(file.exists("quads.r")){
  file.remove("quads.r")
}
save(quads,file="quads.r")
print("Finished saving quadgrams")

### END
print("Returning to main directory!")
setwd(prj.dir)
print(paste("Current directory: ",getwd()))

print("Completed guessDB.R")
