# Capstone Project
# File: makeTMS.R
#   Builds the the document text matrices (DTMS) and text document matrices (TDMS)
#   Loads clean.corpus generated by makeCorpus.R

print("Started script: makeTMS.R")
# Got to project directory and load tools
prj.dir <- file.path(Sys.getenv("HOME"),"git","NLPCapstone")
setwd(prj.dir)
print(paste("Current directory: ",getwd()))

# load resources
source("nlpTools.R")
print("Loaded tools.")

#Switch to processed corpus directory
source("toProcCorpusDir.R")
print(paste("Switched to diretory",getwd()))

#Select corpus directory. THIS IS REQUIRED
corpus.dir <- c("../XX.dir")
print(paste("Going to directory containing corpus: ",corpus.dir))
setwd(corpus.dir)

# Loading corpus
load("corpus.r")
corps <- paste(dir(pattern="corpus"))
print(paste("Loaded corpus: ", corps))

print("***Generating Document Text Matrices***")
# Second, Generate DTMS for clean corpus
print("Generating DTMS for clean corpus.")
dtms <- lapply(clean.corpus,buildDTM) # using default 4-gram as maximum
for(k in seq_along(clean.corpus)){
  names(dtms[[k]])<- c("unigram","bigram","trigram","quadgram")
}

print("Saving DTMS.")
if(file.exists("dtms.r")){
  file.remove("dtms.r")
}
save(dtms,file="dtms.r")
print("Finished saving DTMS.")

print("***Generating Text Document Matrices***")
tdms <- lapply(clean.corpus,buildTDM)
for(k in seq_along(clean.corpus)){
  names(tdms[[k]])<- c("unigram","bigram","trigram","quadgram")
}

print("Saving TDMS.")
if(file.exists("tdms.r")){
  file.remove("tdms.r")
}
save(tdms,file="tdms.r")
print("Finished saving TDMS.")

print("Completed makeTMS.R")

print("Resetting to project directory.")
setwd(prj.dir)


