# Capstone Project
# File: makeCorpus.R
#   Reads files created by fixRawData.R
#        proc/unix.blogs.txt, proc/unix.news.txt, proc/unix.twitter.txt
#   Generates the Corpus object, and cleans it.
#   Saves the cleaned corpus

#### REQUIRED TO SELECT DIRECTORY WHERE TO SAVE CORPUS - SEE END ###

print("Started script: makeCorpus.R")
# Got to project directory and load tools
prj.dir <- file.path(Sys.getenv("HOME"),"git","NLPCapstone")
setwd(prj.dir)
print(paste("Current directory: ",getwd()))

# load resources
source("nlpTools.R")
print("Loaded tools.")

#Switch to processed corpus directory
source("toProcCorpusDir.R")
print(paste("Switched to diretory",getwd()))

# proc.corpus.dir set in toProcCorpusDir.R
text.files <- c("unix.blogs.txt", "unix.news.txt", "unix.twitter.txt")
print(paste("Processed Corpus Directory Files: ",paste0(text.files,collapse=", ")))

# select only a fraction of the processed corpus
# In this case % of the original data for each file.
# s.text is a list with each element one sample of the corpus
# the corpus consists of 3 files of text.
pcent <- c(0.01,0.05,0.10)
if(length(pcent) == 1 & pcent == 1.0){
  s.text <- list("1.0"=lapply(text.files, read.txt))
  names(s.text[[1]]) <- text.files
} else {
  s.text <- lapply(pcent,sampleText,text.files)
}

# Building corpus from sample files generated by sampleText function.
corpus <- lapply(s.text,buildCorpus)

# release some memory
rm(s.text)

# Structure of corpus:
# This is a list. Each element corresponds to a sample.
# Each sample is an list containing an object, one for each text file (a document)
# The object contains two data members, content and meta, for the text file.
#
# For example, to access the text of text file 2 in sample 1:
#   corpus[[1]][2]$content
#
# The content is a character vector with multiple entries with multiple
# lines of text per entry in the vector.

# Perform operations on the corpus
# First clean it.
clean.corpus <- lapply(corpus,purify.corpus,
                       toASCII=TRUE,collapseContractions=TRUE,
                       collapseHyphens=TRUE,removeStopWords=FALSE,stemWords=FALSE)
#  put in file names
for(j in seq(clean.corpus)){
  for(k in seq(clean.corpus[[j]])){ 
    meta(clean.corpus[[j]][[k]],"id") <- text.files[k]
  }
}

save.corpus.dir <- c("../100.dir")
print(paste("Moving to directory before saving corpus:",save.corpus.dir))
setwd(save.corpus.dir)

print("Saving raw corpus and clean corpus.")
print(paste("Using directory:",getwd()))

if(file.exists("corpus.r")){
  file.remove("corpus.r")
}
save(corpus,clean.corpus,file="corpus.r")
print("Finished saving corpus stuff.")

print("Completed makeCorpus.R")

print("Resetting to project directory.")
setwd(prj.dir)
