[1] "Started script: makeTMSsimple.R"
[1] "Current directory:  /Users/gamercier/git/NLPCapstone"
[1] "Loaded tm library."
[1] "Current directory:  /Users/gamercier/git/NLPCapstone/nlpData.dir/final/proc"
[1] "Switched to diretory /Users/gamercier/git/NLPCapstone/nlpData.dir/final/proc"
[1] "Going to directory containing corpus:  ../10.dir"
[1] "Loaded corpus:  corpus.r"
[1] "releasing non clean corpus."
[1] "***Generating Document Text Matrices***"
[1] "Generating DTMS for clean corpus."
[1] "Saving DTMS for unigram"
[1] "Finished saving DTMS in file dtms_1.r"
[1] "Releasing memory..."
[1] "Memory free!"
[1] "Saving DTMS for bigram"
[1] "Finished saving DTMS in file dtms_2.r"
[1] "Releasing memory..."
[1] "Memory free!"
[1] "Saving DTMS for trigram"
[1] "Finished saving DTMS in file dtms_3.r"
[1] "Releasing memory..."
[1] "Memory free!"
[1] "Saving DTMS for quadgram"
[1] "Finished saving DTMS in file dtms_4.r"
[1] "Releasing memory..."
[1] "Memory free!"
[1] "Completed makeTMSsimple.R"
[1] "Resetting to project directory."
